// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflTq0XTLpe5_wFFWWzy9RrbwkjWuP14o',
    appId: '1:432405933324:web:7098f7baed752074712d29',
    messagingSenderId: '432405933324',
    projectId: 'bloodbank-fb4c2',
    authDomain: 'bloodbank-fb4c2.firebaseapp.com',
    storageBucket: 'bloodbank-fb4c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYP8AlCfcubfPLQQS_oHat6LHUWiKzQnA',
    appId: '1:432405933324:android:32533778d6228558712d29',
    messagingSenderId: '432405933324',
    projectId: 'bloodbank-fb4c2',
    storageBucket: 'bloodbank-fb4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvd8Uti0wTuSUAwlKinSiHAoRIE7IpOM',
    appId: '1:432405933324:ios:a62855e1515fa796712d29',
    messagingSenderId: '432405933324',
    projectId: 'bloodbank-fb4c2',
    storageBucket: 'bloodbank-fb4c2.appspot.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvd8Uti0wTuSUAwlKinSiHAoRIE7IpOM',
    appId: '1:432405933324:ios:a62855e1515fa796712d29',
    messagingSenderId: '432405933324',
    projectId: 'bloodbank-fb4c2',
    storageBucket: 'bloodbank-fb4c2.appspot.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCflTq0XTLpe5_wFFWWzy9RrbwkjWuP14o',
    appId: '1:432405933324:web:70a063bc05bfd5bd712d29',
    messagingSenderId: '432405933324',
    projectId: 'bloodbank-fb4c2',
    authDomain: 'bloodbank-fb4c2.firebaseapp.com',
    storageBucket: 'bloodbank-fb4c2.appspot.com',
  );
}
